spring:
  profiles:
    active:
    - dev
  session:
    store-type: jdbc
  jpa:
    database-platform: h2
    database: h2
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: false
  datasource:
    jmx-enabled: true
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password: 
    driver-class-name: org.h2.Driver