spring:
  profiles:
    active:
    - mysql
  session:
    store-type: jdbc
  jpa:
    hibernate:
      naming:
        strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
token:
  expiration: 600000
  secret: przodownikR1
server:
  port: 8081
  session:
    cookie:
      http-only: true
      secure: true
customSecurity:
  concurrent-session-number: 1
  auth-base-url: '/auth/**'
  default-role: user
cors-origins: '*'

liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.xml
  enabled: false
